title: "Data Playground"

description: "Mary van Valkenburg"
logo: "/assets/images/mary-tree.jpg"
google_analytics: 
location: "Nashville, TN"
theme: jekyll-theme-minimal
twitter:
  username: "MaryLvV"
links:
  - "https://www.linkedin.com/in/marylvv/"
  - "http://nashvillesoftwareschool.com/community/instructors/"
gems:
  - jekyll-mentions
