---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<h1 style = "color: darkblue; font-size: 16pt"> Coursera - Johns Hopkins Data Science Specialization </h1>

I earned this certification over an 18-month period from August 2014 to February 2016, completing coursework on Getting and Cleaning Data, Exploratory Data Analysis, Reproducible Research, Statistical Inference, Regression Models, Machine Learning, and Developing Data Products using the R programming language.

<h2 style = "color: steelblue; font-size: 12pt"> Shiny Vendor Payments </h2>
- As part of this study, I created two Shiny apps.  The first was a simple data filter to view payments by the state of Tennessee by agency and fiscal year (https://marylvv.shinyapps.io/Shiny-VendorPayments/).  

<h2 style = "color: steelblue; font-size: 12pt"> Predict-A-Tron 3000 </h2>
- This second Shiny app was an outcome of the specialization's capstone project.  It implements a next word prediction algorithm I constructed based on the Markov assumption.  The data for this project originated in three separate corpora of tweets, news, and blog posts. After creating tables of n-grams and their frequency counts, the algorithm applies Katz's backoff principle (searching the last three words in the 4-gram table, followed by a search of the last two words in the trigram table, and finally the last single word in the bigram table) to find the most likely next word given the input text (https://marylvv.shinyapps.io/PredictATron3000/).



<h1 style = "color: darkblue; font-size: 16pt"> Lipscomb MSDS Project </h1>
<h2 style = "color: steelblue; font-size: 12pt"> Sentiment Analysis of Twitter Data & Newspaper Letters-to-the-Editor to Detect Learned Helplessness in the Public Sphere </h2>
- For the thesis project, I performed sentiment analysis on tweets and newspaper letters-to-the-editor that were published in the 30 days following mass school shootings (shootings in which 4 or more people were killed) at
    - Columbine High School (Littleton, CO) April 20, 1999
    - Amish School (Nickel Mines, PA) October 2, 2006 
    - Virginia Tech (Blacksburg, VA) April 16, 2007 
    - Sandy Hook Elementary (Newtown, CT) December 14, 2012 
    - Umpqua Community College (Roseburg, OR) October 1, 2015 

- My hypothesis in this study was that we would see societal learned helplessness as evidenced by both a muting of sentiment (particularly anger) and a decline overall in response to these events.

- You can read more about the data pipeline for this project here (datapipeline.pptx)

