---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<h1 style = "color: black; font-size: 18pt"> Data Projects </h1>

<h2 style = "color: darkgreen; font-size: 14pt"> Lipscomb MSDS Project </h2>
The Lipscomb University Data Science Masters Program included coursework in Principles of Data Science, Information Structures, Principles of Statistical Analysis & Decision Modeling, Research Methods, Big Data Management & Analytics, Data Mining and Analysis, Predictive Analytics and Data Mining, Case Studies in Data Science, and a two part practicum in designing and executing a data science project.
<h2 style = "color: darkblue; font-size: 12pt"> Sentiment Analysis of Twitter Data & Newspaper Letters-to-the-Editor to Detect Learned Helplessness in the Public Sphere </h2>
- For the thesis project, with my research partner, I performed sentiment analysis on tweets and newspaper letters-to-the-editor that were published in the 30 days following mass school shootings (shootings in which 4 or more people were killed) at
    - Columbine High School (Littleton, CO) April 20, 1999
    - Amish School (Nickel Mines, PA) October 2, 2006 
    - Virginia Tech (Blacksburg, VA) April 16, 2007 
    - Sandy Hook Elementary (Newtown, CT) December 14, 2012 
    - Umpqua Community College (Roseburg, OR) October 1, 2015 

- Our hypothesis in this study was that we would see societal learned helplessness as evidenced by both a muting of sentiment (particularly anger) and a decline overall in response to these events.

- You can read more about the data pipeline for this project here (http://bit.ly/schoolshootingdata)
<br>

<h2 style = "color: darkgreen; font-size: 14pt"> Coursera - Johns Hopkins Data Science Specialization </h2>
This certification included coursework on Getting and Cleaning Data, Exploratory Data Analysis, Reproducible Research, Statistical Inference, Regression Models, Machine Learning, and Developing Data Products using the R programming language.  Below are three projects I completed on as part of this effort.

<h2 style = "color: darkblue; font-size: 12pt"> Predicting Correctness of Technique for Weightlifters</h2>
- This prediction exercise (/PML_Project.html) was part of the Practical Machine Learning course. A model was trained using Random Forest to predict the correctness of technique given feedback data collected from wearable sensors that showed an individual's weightlifting mechanics.  The data was provided by Groupware@LES, and is available online at http://groupware.les.inf.puc-rio.br/har 

<h2 style = "color: darkblue; font-size: 12pt"> Shiny Vendor Payments </h2>
- My first Shiny app was a simple data filter to view payments to vendors by the state of Tennessee by agency and fiscal year (https://marylvv.shinyapps.io/Shiny-VendorPayments/).  

<h2 style = "color: darkblue; font-size: 12pt"> Predict-A-Tron 3000 </h2>
- My second Shiny app was part of the specialization's capstone project.  It implements a next word prediction algorithm I constructed based on the Markov assumption.  The data for this project originated in three separate corpora of tweets, news, and blog posts. After creating tables of n-grams and their frequency counts, the algorithm applies Katz's backoff principle (searching the last three words in the 4-gram table, followed by a search of the last two words in the trigram table, and finally the last single word in the bigram table) to find the most likely next word given the input text (https://marylvv.shinyapps.io/PredictATron3000/).
<br>

<h1 style = "color: darkgreen; font-size: 14pt"> Just for Fun </h1>
<h2 style = "color: darkblue; font-size: 12pt"> Chicken Permits in Metro Nashville</h2>
- Using Nashville Open Data (https://data.nashville.gov/) and Carto (https://carto.com/) maps, I created this visualization of where the chickens are: https://bit.ly/nashvillechickens



